build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
            environment:
                php:
                    version: 8.2

filter:
    paths: ["src/*"]
