language: php

php:
  - 5.4

env:
  - GUZZLE_VERSION="3.1.*"
  - GUZZLE_VERSION="3.8.*"

before_install:
 - composer selfupdate
 - composer require guzzle/guzzle:${GUZZLE_VERSION}
 - composer install
 - 'wget http://pecl.php.net/get/APC ; tar -xzf APC ; sh -c "cd APC-* && phpize && ./configure  && make && sudo make install" ; echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`'
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit --coverage-text
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 src); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  email: false
